---
abstract: 'An XS++ plugin for controlling cloning on thread creation'
author:
  - 'Steffen Mueller <smueller@cpan.org>'
build_requires:
  Module::Build: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3605'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ExtUtils-XSpp-Plugin-Cloning
provides:
  ExtUtils::XSpp::Plugin::Cloning:
    file: lib/ExtUtils/XSpp/Plugin/Cloning.pm
    version: 0.01
requires:
  ExtUtils::XSpp: 0.11_02
  perl: v5.6.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
